### ISSUE TITLE
Unexpected Exception beim Filter

### ISSUE THREAD

**Issue by mapfde** [wisslab/yalani#2]
Suche nach "Last modified" "is not" mit leerem Feld führt zur Exception

**Comment by kaiec** [comment]
Eventuell das gleiche Problem: anywhere kann im Filter-Fenster nicht verwendet werden, gibt eine Nullpointerexception.

**Comment by kaiec** [comment]
Das ist das gleiche Problem, anywhere und last modified müssen beim Filter-panel ausgeblendet werden. Last modified auch beim Schnellfilter rausnehmen, da geht es auch nicht (wurde auch nie implementiert)!
