### ISSUE TITLE
Verbesserung der "bigger" Suche

### ISSUE THREAD

**Issue by mapfde** [wisslab/yalani#4]
Suchen nach "bigger" und "smaller" sind für Jahresangaben sehr sinnvoll. Die Felder enthalten leider oft neben den Jahresangaben noch zusätzliche Zeichen, z.B. eckige Klammern, "circa".

Beim Import könnten diese soweit entfernt werden, dass das Feld soweit möglich direkt mit einer Jahreszahl beginnt.

**Comment by kaiec** [comment]
Ist im Knime Workflow für Saarbrücken umgesetzt.
