### ISSUE TITLE
Sanduhr

### ISSUE THREAD

**Issue by mapfde** [wisslab/yalani#5]
Viele Operationen dauern länger, ein visuelles Feedback, dass das Programm noch lebt wäre wichtig

**Comment by mapfde** [comment]
Typisches Beispiel sind das Einfärben der Klassen.

**Comment by kaiec** [comment]
Dazu müssten die entsprechenden Teile in Hintergrund-Tasks ausgelagert werden, Beispiele dafür gibt es, z.B. in Semtinel. Vorerst sind dafür leider keine Ressourcen frei.
